apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: live2-airflow-git-sync-pvc
spec:
  storageClassName: local-airflow-git-sync
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
