apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
  namespace: airflow
spec:
  storageClassName: dags-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
