apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
  labels:
    type: airflow-workers
spec:
  storageClassName: logs-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs/airflow/logs
    server: live1
