apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
  namespace: airflow
spec:
  storageClassName: logs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
