apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-workers-pvc
  namespace: airflow
spec:
  storageClassName: workers-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
