---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3fs-airflow-worker-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/s3-bucket/liveget/airflow/worker
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-worker
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3fs-airflow-logs-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/s3-bucket/liveget/airflow/logs
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-logs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: master-airflow-redis-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  local:
    path: /mnt/airflow/redis
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: live2-airflow-redis-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  local:
    path: /mnt/airflow/redis
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - live2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: live1-airflow-redis-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  local:
    path: /mnt/airflow/redis
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - live1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3fs-airflow-git-sync-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/s3-bucket/liveget/airflow/git-sync/dags
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-git-sync
