---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: live1-airflow-worker-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /mnt/airflow/worker
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-worker
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - live1 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: live2-airflow-worker-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /mnt/airflow/worker
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-worker
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - live2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: master-airflow-worker-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /mnt/airflow/worker
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-worker
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: live1-airflow-logs-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  local:
    path: /mnt/airflow/logs
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - live1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: live2-airflow-logs-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  local:
    path: /mnt/airflow/logs
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - live2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: master-airflow-logs-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  local:
    path: /mnt/airflow/logs
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: master-airflow-redis-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /mnt/airflow/redis
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: live2-airflow-redis-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /mnt/airflow/redis
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - live2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: live1-airflow-redis-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /mnt/airflow/redis
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - live1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: master-airflow-git-sync-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /mnt/airflow/git-sync
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-git-sync
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: live2-airflow-git-sync-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /mnt/airflow/git-sync
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-git-sync
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - live2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: live1-airflow-git-sync-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /mnt/airflow/git-sync
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-airflow-git-sync
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - live1
